/**
 * @jest-environment node
 *
 * Lock in the Expo app.json icon configuration. APP-38 swapped the
 * Android adaptive-icon background from the placeholder light blue to the
 * canvas dark token, dropped the placeholder backgroundImage in favour of
 * a solid colour, and points every asset path at the regenerated BrandGlyph
 * PNGs. These tests guard against accidental regression of that wiring.
 */

import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import appJson from './app.json';

type SplashPluginConfig = {
    image: string;
    imageWidth: number;
    resizeMode: string;
    backgroundColor: string;
    dark?: { backgroundColor: string };
};

type BuildPropertiesPluginConfig = {
    android?: {
        networkSecurityConfig?: string;
    };
};

function findSplashPlugin(): SplashPluginConfig {
    const plugins = appJson.expo.plugins;
    for (const entry of plugins) {
        if (Array.isArray(entry) && entry[0] === 'expo-splash-screen') {
            return entry[1] as SplashPluginConfig;
        }
    }
    throw new Error('expo-splash-screen plugin not configured in app.json');
}

function findBuildPropertiesPlugin(): BuildPropertiesPluginConfig {
    const plugins = appJson.expo.plugins;
    for (const entry of plugins) {
        if (Array.isArray(entry) && entry[0] === 'expo-build-properties') {
            return entry[1] as BuildPropertiesPluginConfig;
        }
    }
    throw new Error('expo-build-properties plugin not configured in app.json');
}

describe('app.json icon configuration', () => {
    it('pins the Android adaptive-icon background to the canvas-dark design token (#06090A).', () => {
        expect(appJson.expo.android.adaptiveIcon.backgroundColor).toBe('#06090A');
    });

    it('uses a solid background colour for the Android adaptive icon (no backgroundImage).', () => {
        // The placeholder backgroundImage path was removed in APP-38 — the
        // ticket calls for a solid colour, not a custom background bitmap.
        expect((appJson.expo.android.adaptiveIcon as { backgroundImage?: string }).backgroundImage).toBeUndefined();
    });

    it('points every icon asset path at a file that exists in the repo.', () => {
        const projectRoot = __dirname;
        const candidates: ReadonlyArray<string> = [
            appJson.expo.icon,
            appJson.expo.android.adaptiveIcon.foregroundImage,
            appJson.expo.android.adaptiveIcon.monochromeImage,
            findSplashPlugin().image,
        ];

        for (const relativePath of candidates) {
            // Paths in app.json are written like './assets/images/icon.png'.
            const absolute = resolve(projectRoot, relativePath);
            expect(existsSync(absolute)).toBe(true);
        }
    });
});

describe('app.json splash configuration', () => {
    it('paints the splash on the canvas-dark token in every appearance state (APP-53).', () => {
        // Setting `backgroundColor` to the dark token at the top level (no
        // `dark` override) ensures the iOS launchscreen never momentarily
        // flashes white before the OS settles on dark mode.
        expect(findSplashPlugin().backgroundColor).toBe('#06090A');
    });

    it('omits the light/dark override now that the base colour is dark (APP-53).', () => {
        expect(findSplashPlugin().dark).toBeUndefined();
    });

    it('renders the radar-mark splash image at 200dp via contain resize.', () => {
        const plugin = findSplashPlugin();
        expect(plugin.image).toBe('./assets/images/splash-icon.png');
        expect(plugin.imageWidth).toBe(200);
        expect(plugin.resizeMode).toBe('contain');
    });
});

describe('app.json Android network-security configuration (APP-63)', () => {
    it('wires expo-build-properties to point at the network-security-config source XML.', () => {
        const config = findBuildPropertiesPlugin();
        expect(config.android?.networkSecurityConfig).toBe('./network-security-config.xml');
    });

    it('keeps the referenced source XML in the repo (prebuild copies it into android/ at build time).', () => {
        // `app/android/` is gitignored — regenerated by `expo prebuild` from
        // the plugin config — so we only assert on the tracked source.
        const sourcePath = resolve(__dirname, 'network-security-config.xml');
        expect(existsSync(sourcePath)).toBe(true);
    });

    it('locks in the LAN-only cleartext policy: base config HTTPS-only, single domain entry for the API host.', () => {
        const xml = readFileSync(
            resolve(__dirname, 'network-security-config.xml'),
            'utf8',
        );

        // Default: every destination is HTTPS-only.
        expect(xml).toMatch(/<base-config\b[^>]*cleartextTrafficPermitted="false"/);

        // Allowed: cleartext to the home API host.
        expect(xml).toMatch(
            /<domain-config\b[^>]*cleartextTrafficPermitted="true"[\s\S]*?<domain[^>]*>192\.168\.2\.100<\/domain>/,
        );
    });
});
