const plugin = require('tailwindcss/plugin');

const fontDisplay = ['Bricolage Grotesque', 'ui-sans-serif', 'system-ui', 'sans-serif'].join(', ');
const fontBody = ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'].join(', ');
const fontMono = ['Geist Mono', 'ui-monospace', 'SF Mono', 'Menlo', 'monospace'].join(', ');

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './app/**/*.{js,jsx,ts,tsx}',
        './components/**/*.{js,jsx,ts,tsx}',
    ],
    presets: [require('nativewind/preset')],
    theme: {
        extend: {
            colors: {
                // Ink ramp (raw).
                'ink-0': '#04060500',
                'ink-50': '#06090A',
                'ink-100': '#0B1110',
                'ink-200': '#0E1412',
                'ink-300': '#141B18',
                'ink-400': '#1B231F',
                'ink-500': '#232E29',
                'ink-600': '#344239',
                'ink-700': '#495A50',

                // Chalk ramp (raw).
                'chalk-50': '#ECF1ED',
                'chalk-200': '#C7CFC9',
                'chalk-400': '#8A9690',
                'chalk-600': '#5A6862',
                'chalk-800': '#3A4641',

                // Grass ramp (raw) + glow.
                'grass-300': '#B7F0CB',
                'grass-400': '#8FEAB1',
                'grass-500': '#6FE39B',
                'grass-600': '#4FCB7E',
                'grass-700': '#2C8F5A',
                'grass-900': '#0F2A1C',
                'grass-glow': 'rgba(111, 227, 155, 0.18)',
                'grass-glow-2': 'rgba(111, 227, 155, 0.06)',

                // Accent supplemental.
                'water-500': '#7CD4FB',
                'water-700': '#2E7FA8',
                'amber-500': '#FFBE6B',
                'amber-700': '#B07B2A',
                'rose-500': '#FF6B7B',
                'rose-700': '#A23744',
                'moon-500': '#D8C690',

                // Semantic.
                bg: '#06090A',
                'bg-alt': '#0B1110',
                surface: '#0E1412',
                'surface-2': '#141B18',
                elevated: '#1B231F',
                hairline: '#232E29',
                border: '#232E29',
                'border-strong': '#344239',
                fg: '#ECF1ED',
                'fg-soft': '#C7CFC9',
                'fg-muted': '#8A9690',
                'fg-dim': '#5A6862',
                'fg-faint': '#3A4641',
                accent: '#6FE39B',
                'accent-press': '#4FCB7E',
                'accent-deep': '#2C8F5A',
                'accent-glow': 'rgba(111, 227, 155, 0.18)',
                info: '#7CD4FB',
                warn: '#FFBE6B',
                danger: '#FF6B7B',
                'on-accent': '#052013',

                // Depletion ramp (saturated → past RAW).
                'depletion-0': '#6FE39B',
                'depletion-1': '#9CE093',
                'depletion-2': '#C8DD7B',
                'depletion-3': '#E9C96D',
                'depletion-4': '#FFBE6B',
                'depletion-5': '#FF9B6F',
                'depletion-6': '#FF6B7B',
            },
            spacing: {
                's-1': '4px',
                's-2': '8px',
                's-3': '12px',
                's-4': '16px',
                's-5': '20px',
                's-6': '24px',
                's-7': '32px',
                's-8': '40px',
                's-9': '48px',
                's-10': '64px',
                's-11': '80px',
                's-12': '96px',
            },
            borderRadius: {
                'r-1': '4px',
                'r-2': '4px',
                'r-3': '4px',
                'r-4': '4px',
                'r-5': '4px',
                'r-pill': '4px',
            },
            boxShadow: {
                1: '0 1px 0 0 rgba(255, 255, 255, 0.03) inset, 0 1px 2px rgba(0, 0, 0, 0.4)',
                2: '0 1px 0 0 rgba(255, 255, 255, 0.04) inset, 0 4px 14px rgba(0, 0, 0, 0.45), 0 1px 2px rgba(0, 0, 0, 0.3)',
                3: '0 1px 0 0 rgba(255, 255, 255, 0.05) inset, 0 20px 48px rgba(0, 0, 0, 0.6), 0 4px 10px rgba(0, 0, 0, 0.4)',
                'glow-accent': '0 0 0 1px rgba(111, 227, 155, 0.28) inset, 0 0 24px -4px rgba(111, 227, 155, 0.18)',
            },
            fontFamily: {
                display: ['Bricolage Grotesque', 'ui-sans-serif', 'system-ui', 'sans-serif'],
                body: ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
                mono: ['Geist Mono', 'ui-monospace', 'SF Mono', 'Menlo', 'monospace'],
            },
            fontSize: {
                'display-1': ['56px', { lineHeight: '0.96', letterSpacing: '-0.02em', fontWeight: '700' }],
                'display-2': ['40px', { lineHeight: '1.02', letterSpacing: '-0.018em', fontWeight: '600' }],
                'display-3': ['28px', { lineHeight: '1.08', letterSpacing: '-0.015em', fontWeight: '600' }],
                'h-1': ['22px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
                'h-2': ['18px', { lineHeight: '1.25', letterSpacing: '-0.005em', fontWeight: '600' }],
                'h-3': ['15px', { lineHeight: '1.3', fontWeight: '600' }],
                eyebrow: ['11px', { lineHeight: '1.2', letterSpacing: '0.14em', fontWeight: '500' }],
                label: ['12px', { lineHeight: '1.3', fontWeight: '500' }],
                'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
                body: ['14px', { lineHeight: '1.5', fontWeight: '400' }],
                'body-sm': ['12px', { lineHeight: '1.45', fontWeight: '400' }],
                'num-hero': ['72px', { lineHeight: '0.95', letterSpacing: '-0.04em', fontWeight: '500' }],
                'num-lg': ['28px', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '500' }],
                num: ['14px', { lineHeight: '1.2', fontWeight: '500' }],
                'num-sm': ['11px', { lineHeight: '1.2', fontWeight: '500' }],
            },
            transitionDuration: {
                1: '120ms',
                2: '220ms',
                3: '360ms',
            },
            transitionTimingFunction: {
                'ease-out': 'cubic-bezier(0.2, 0.7, 0.2, 1)',
                'ease-in-out': 'cubic-bezier(0.6, 0, 0.2, 1)',
            },
        },
    },
    plugins: [
        plugin(function ({ addComponents }) {
            addComponents({
                '.display-1': {
                    fontFamily: fontDisplay,
                    fontSize: '56px',
                    lineHeight: '0.96',
                    fontWeight: '700',
                    letterSpacing: '-0.02em',
                },
                '.display-2': {
                    fontFamily: fontDisplay,
                    fontSize: '40px',
                    lineHeight: '1.02',
                    fontWeight: '600',
                    letterSpacing: '-0.018em',
                },
                '.display-3': {
                    fontFamily: fontDisplay,
                    fontSize: '28px',
                    lineHeight: '1.08',
                    fontWeight: '600',
                    letterSpacing: '-0.015em',
                },
                '.h1': {
                    fontFamily: fontDisplay,
                    fontSize: '22px',
                    lineHeight: '1.2',
                    fontWeight: '600',
                    letterSpacing: '-0.01em',
                },
                '.h2': {
                    fontFamily: fontDisplay,
                    fontSize: '18px',
                    lineHeight: '1.25',
                    fontWeight: '600',
                    letterSpacing: '-0.005em',
                },
                '.h3': {
                    fontFamily: fontBody,
                    fontSize: '15px',
                    lineHeight: '1.3',
                    fontWeight: '600',
                },
                '.eyebrow': {
                    fontFamily: fontBody,
                    fontSize: '11px',
                    lineHeight: '1.2',
                    fontWeight: '500',
                    textTransform: 'uppercase',
                    letterSpacing: '0.14em',
                    color: '#8A9690',
                },
                '.label': {
                    fontFamily: fontBody,
                    fontSize: '12px',
                    lineHeight: '1.3',
                    fontWeight: '500',
                    color: '#8A9690',
                },
                '.body-lg': {
                    fontFamily: fontBody,
                    fontSize: '16px',
                    lineHeight: '1.5',
                    fontWeight: '400',
                },
                '.body': {
                    fontFamily: fontBody,
                    fontSize: '14px',
                    lineHeight: '1.5',
                    fontWeight: '400',
                },
                '.body-sm': {
                    fontFamily: fontBody,
                    fontSize: '12px',
                    lineHeight: '1.45',
                    fontWeight: '400',
                    color: '#C7CFC9',
                },
                '.num-hero': {
                    fontFamily: fontMono,
                    fontSize: '72px',
                    lineHeight: '0.95',
                    fontWeight: '500',
                    letterSpacing: '-0.04em',
                    fontFeatureSettings: '"ss01", "tnum"',
                },
                '.num-lg': {
                    fontFamily: fontMono,
                    fontSize: '28px',
                    lineHeight: '1',
                    fontWeight: '500',
                    letterSpacing: '-0.02em',
                    fontFeatureSettings: '"tnum"',
                },
                '.num': {
                    fontFamily: fontMono,
                    fontSize: '14px',
                    lineHeight: '1.2',
                    fontWeight: '500',
                    fontFeatureSettings: '"tnum"',
                },
                '.num-sm': {
                    fontFamily: fontMono,
                    fontSize: '11px',
                    lineHeight: '1.2',
                    fontWeight: '500',
                    fontFeatureSettings: '"tnum"',
                },
            });
        }),
    ],
};
